spring.application.name=RealTimeCracow

# GTFS API
gtfs.base-url=https://gtfs.ztp.krakow.pl
# SQLite Database
gtfs.database.path=./data/gtfs.db
spring.datasource.url=jdbc:sqlite:${gtfs.database.path}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# GTFS Refresh Schedule (every 6 hours)
gtfs.refresh.cron=0 0 */6 * * *
gtfs.refresh.on-startup=true

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method


spring.codec.max-in-memory-size=50MB


# GTFS File Names
gtfs.files.stops=stops.txt
gtfs.files.routes=routes.txt
gtfs.files.trips=trips.txt
gtfs.files.stop-times=stop_times.txt
gtfs.files.calendar=calendar.txt
gtfs.files.calendar-dates=calendar_dates.txt



#Spring AI

spring.ai.mcp.server.name=realtime-cracow-mcp
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.sse-endpoint=/sse
spring.ai.mcp.server.sse-message-endpoint=/mcp/message